# Generated by Django 5.1.1 on 2024-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
