# Generated by Django 5.1.2 on 2024-11-13 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_alter_superhero_image_investigator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='bio',
        ),
        migrations.AddField(
            model_name='investigator',
            name='name',
            field=models.CharField(default='Def Name', max_length=200),
        ),
        migrations.AddField(
            model_name='investigator',
            name='superhero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigator', to='hero.superhero'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigator', to=settings.AUTH_USER_MODEL),
        ),
    ]
