# Generated by Django 5.1.2 on 2024-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_rename_body_article_markdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='html',
        ),
        migrations.RemoveField(
            model_name='article',
            name='markdown',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(blank=True, default='superheroes/default_image.jpg', null=True, upload_to='superheroes/'),
        ),
    ]
