# Generated by Django 5.1.2 on 2024-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_remove_article_html_remove_article_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='no content', max_length=5000),
        ),
    ]
