# Generated by Django 5.1.2 on 2024-11-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_alter_article_body'),
        ('photos', '__first__'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
