envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: webapps-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Chav74/PythonWebApps
  source_dir:Student/Superhero
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: webapps-demo-app
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    python manage.py loaddata hero.json
    gunicorn config.wsgi:application --worker-tmp-dir /dev/shm
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Chav74/PythonWebApps
  
  routes:
  - path: /static
  source_dir: Student/Superhero/static
