envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "False"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: webapps-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: production
    deploy_on_push: true
    repo: Chav74/PythonWebApps
  source_dir:/Student/Superhero
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: Chav74-app
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    python manage.py loaddata hero.json
    python manage.py build books
    gunicorn config.wsgi:application --worker-tmp-dir /dev/shm config.wsgi
static_sites:
- environment_slug: html
  github:
    branch: production
    deploy_on_push: true
    repo: Chav74/PythonWebApps
  name: chav74-app-static
  routes:
  - path: /static
  source_dir: /static
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
services:
- environment_slug: python
  envs:
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
domains:
- domain: https://octopus-app-8adbk.ondigitalocean.app
  type: PRIMARY
  zone: https://octopus-app-8adbk.ondigitalocean.app
- domain: https://octopus-app-8adbk.ondigitalocean.app/accounts/login/
  type: ALIAS
  zone: https://octopus-app-8adbk.ondigitalocean.app/accounts/login/
name: Chav74-app 
region: nyc